version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: schedule
    ports:
      - '5432:5432'