# Generated by Django 4.0.4 on 2022-06-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='students',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.courses', verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.departments', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_educational_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.educationalforms', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.groups', verbose_name='Группа'),
        ),
    ]
