# Generated by Django 4.0.4 on 2022-06-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleSystem', '0002_news_alter_students_id_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.courses', verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.departments', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_educational_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.educationalforms', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ScheduleSystem.groups', verbose_name='Группа'),
        ),
    ]
