# Generated by Django 4.0.4 on 2022-06-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleSystem', '0005_remove_news_views_alter_attendance_date_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='image_subject',
            field=models.ImageField(default='subjects_images/default.png', upload_to='subjects_images/'),
        ),
    ]
