# Generated by Django 4.1.7 on 2023-03-17 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.course', verbose_name='Номер курса'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.department', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_educational_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.educationalform', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timesheets.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин студента'),
        ),
    ]
