# Generated by Django 4.1.7 on 2023-03-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='id_week_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.weekday', verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.lessontime'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject'),
        ),
    ]
