# Generated by Django 4.1.7 on 2023-03-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('hours', models.IntegerField(default=1, verbose_name='Часы')),
                ('exam_form', models.CharField(max_length=20, verbose_name='Экзаменационная форма')),
                ('image_subject', models.ImageField(default='subjects_images/default.jpg', upload_to='subjects_images/')),
                ('num_cub', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['-id'],
            },
        ),
    ]
