# Generated by Django 4.1.7 on 2023-03-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=50, verbose_name='Название предмета')),
                ('hours', models.IntegerField(default=1, verbose_name='Часы')),
                ('exam_form', models.CharField(max_length=20, verbose_name='Экзаменационная форма')),
                ('image_subject', models.ImageField(default='subjects_images/default.jpg', upload_to='subjects_images/')),
                ('num_cub', models.CharField(blank=True, max_length=20, verbose_name='Кабинет')),
                ('id_course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.course', verbose_name='Курс')),
                ('id_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.department', verbose_name='Название кафедры')),
                ('id_educational_form', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.educationalform', verbose_name='Форма обучения')),
                ('id_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.group', verbose_name='Номер группы')),
                ('id_teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['-id'],
            },
        ),
    ]
