# Generated by Django 4.1.7 on 2023-03-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='id_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.department', verbose_name='Название кафедры'),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_educational_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.educationalform', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.group', verbose_name='Номер группы'),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.teacher', verbose_name='Преподаватель'),
        ),
    ]
