# Generated by Django 4.1.7 on 2023-03-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timesheets', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='id_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.group', verbose_name='Номер группы'),
        ),
        migrations.AddField(
            model_name='subject',
            name='id_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timesheets.teacher', verbose_name='Преподаватель'),
        ),
    ]
